# Write your MySQL query statement below
SELECT
USERS.NAME, IFNULL(SUM(RIDES.DISTANCE), 0) TRAVELLED_DISTANCE
FROM
USERS
LEFT JOIN
RIDES ON USERS.ID = RIDES.USER_ID
GROUP BY
USERS.ID
ORDER BY
SUM(RIDES.DISTANCE) DESC, USERS.NAME ASC