# Write your MySQL query statement below
SELECT
NAME
FROM
SALESPERSON
WHERE
SALES_ID NOT IN(
    SELECT
    DISTINCT(ORDERS.SALES_ID)
    FROM 
    ORDERS
    LEFT JOIN
    COMPANY ON ORDERS.COM_ID = COMPANY.COM_ID
    WHERE
    COMPANY.NAME = 'RED' 
)
