# Write your MySQL query statement below
SELECT
NAME
FROM
SALESPERSON
WHERE
SALES_ID NOT IN(
    SELECT
    DISTINCT(ORDERS.SALES_ID)
    FROM 
    ORDERS, COMPANY
    WHERE
    COMPANY.NAME = 'RED' AND ORDERS.COM_ID = COMPANY.COM_ID
)
