# Write your MySQL query statement below
SELECT
ACTIVITY_DATE DAY, ACTIVE_USERS
FROM(
SELECT
ACTIVITY_DATE, COUNT(DISTINCT(USER_ID)) AS ACTIVE_USERS
FROM
ACTIVITY
GROUP BY
ACTIVITY_DATE
) AS A
WHERE
ACTIVITY_DATE BETWEEN DATE_ADD('2019-07-28', INTERVAL -30 DAY) AND '2019-07-27'