# Write your MySQL query statement below
SELECT
SELL_DATE sell_date, COUNT(DISTINCT(PRODUCT)) num_sold, GROUP_CONCAT(DISTINCT(PRODUCT) ORDER BY PRODUCT ASC) products
FROM
ACTIVITIES
GROUP BY
SELL_DATE
ORDER BY
SELL_DATE

# SELECT
# SALE_DATE, DISTINCT(PRODUCT)
# FROM
# ACTIVITIES
# GROUP BY
# SELL_DATE