# Write your MySQL query statement below
SELECT
DISTINCT(PRODUCT.PRODUCT_ID), PRODUCT.PRODUCT_NAME
FROM
PRODUCT
JOIN
SALES ON SALES.PRODUCT_ID = PRODUCT.PRODUCT_ID
WHERE
SALES.SALE_DATE BETWEEN '2019-01-01' AND '2019-03-31' AND
PRODUCT.PRODUCT_ID NOT IN (
    SELECT
    PRODUCT.PRODUCT_ID
    FROM
    PRODUCT
    JOIN
    SALES ON SALES.PRODUCT_ID = PRODUCT.PRODUCT_ID
    WHERE
    SALES.SALE_DATE NOT BETWEEN '2019-01-01' AND '2019-03-31'
)