# Write your MySQL query statement below
SELECT
*
# U.NAME, SUM(T.AMOUNT) 
# U.NAME, SUM(T.AMOUNT) AS BALANCE
FROM
(
    SELECT
    U.NAME, SUM(T.AMOUNT) BALANCE
    FROM
    USERS U
    RIGHT JOIN
    TRANSACTIONS T ON U.ACCOUNT = T.ACCOUNT
    GROUP BY
    T.ACCOUNT
) TT
WHERE
BALANCE > 10000
# GROUP BY
# T.ACCOUNT