# Write your MySQL query statement below
SELECT
ACTOR_ID, DIRECTOR_ID
FROM
(SELECT
ACTOR_ID, DIRECTOR_ID, COUNT(TIMESTAMP) AS T
FROM
ACTORDIRECTOR
GROUP BY
ACTOR_ID, DIRECTOR_ID) AS ACTORDIRECTOR2
WHERE
T >=3
