# Write your MySQL query statement below
SELECT
V.CUSTOMER_ID, COUNT(V.VISIT_ID) COUNT_NO_TRANS
FROM
VISITS V
LEFT JOIN
TRANSACTIONS T ON V.VISIT_ID = T.VISIT_ID
WHERE 
ISNULL(T.TRANSACTION_ID )
GROUP BY
V.CUSTOMER_ID